### ISSUE TITLE
Project does not have test nor documentation

### ISSUE THREAD

**Issue by martirella** [pauarge/sns-redis#1]
You should add some tests before people really consider using it.

**Comment by pauarge** [comment]
Project is not finished yet, I'm working on it

**Comment by Blutude** [comment]
How is it going? It the project finished? Tested?

**Comment by pauarge** [comment]
Hi @Blutude, I coded this project a while ago and at that time it was used and deployed at scale. I no longer maintain it, but feel free to contribute. Do you need any feature specifically?
